import type { Metadata } from "next";

import { ThemeProvider } from "@/components/theme-provider";
import { inter, lora } from "@/lib/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Oscar Castaneda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${lora.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
